// source: grpc_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

goog.exportSymbol('proto.automatedcodingworkflow.GetWorkflowConfigRequest', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.GetWorkflowConfigResponse', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.SetWorkspacePathRequest', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.SetWorkspacePathResponse', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.Stage', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.StartWorkflowRequest', null, global);
goog.exportSymbol('proto.automatedcodingworkflow.StartWorkflowResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.StartWorkflowRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.automatedcodingworkflow.StartWorkflowRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.StartWorkflowRequest.displayName = 'proto.automatedcodingworkflow.StartWorkflowRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.StartWorkflowResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.automatedcodingworkflow.StartWorkflowResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.StartWorkflowResponse.displayName = 'proto.automatedcodingworkflow.StartWorkflowResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.automatedcodingworkflow.GetWorkflowConfigRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.GetWorkflowConfigRequest.displayName = 'proto.automatedcodingworkflow.GetWorkflowConfigRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.automatedcodingworkflow.GetWorkflowConfigResponse.repeatedFields_, null);
};
goog.inherits(proto.automatedcodingworkflow.GetWorkflowConfigResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.GetWorkflowConfigResponse.displayName = 'proto.automatedcodingworkflow.GetWorkflowConfigResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.Stage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.automatedcodingworkflow.Stage.repeatedFields_, null);
};
goog.inherits(proto.automatedcodingworkflow.Stage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.Stage.displayName = 'proto.automatedcodingworkflow.Stage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.automatedcodingworkflow.SetWorkspacePathRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.SetWorkspacePathRequest.displayName = 'proto.automatedcodingworkflow.SetWorkspacePathRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.automatedcodingworkflow.SetWorkspacePathResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.automatedcodingworkflow.SetWorkspacePathResponse.displayName = 'proto.automatedcodingworkflow.SetWorkspacePathResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.StartWorkflowRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.StartWorkflowRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.StartWorkflowRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.StartWorkflowRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.StartWorkflowRequest}
 */
proto.automatedcodingworkflow.StartWorkflowRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.StartWorkflowRequest;
  return proto.automatedcodingworkflow.StartWorkflowRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.StartWorkflowRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.StartWorkflowRequest}
 */
proto.automatedcodingworkflow.StartWorkflowRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.StartWorkflowRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.StartWorkflowRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.StartWorkflowRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.StartWorkflowRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.StartWorkflowResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.StartWorkflowResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.StartWorkflowResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.StartWorkflowResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    result: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.StartWorkflowResponse}
 */
proto.automatedcodingworkflow.StartWorkflowResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.StartWorkflowResponse;
  return proto.automatedcodingworkflow.StartWorkflowResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.StartWorkflowResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.StartWorkflowResponse}
 */
proto.automatedcodingworkflow.StartWorkflowResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResult(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.StartWorkflowResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.StartWorkflowResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.StartWorkflowResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.StartWorkflowResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getResult();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string result = 1;
 * @return {string}
 */
proto.automatedcodingworkflow.StartWorkflowResponse.prototype.getResult = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.automatedcodingworkflow.StartWorkflowResponse} returns this
 */
proto.automatedcodingworkflow.StartWorkflowResponse.prototype.setResult = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.GetWorkflowConfigRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigRequest}
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.GetWorkflowConfigRequest;
  return proto.automatedcodingworkflow.GetWorkflowConfigRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigRequest}
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.GetWorkflowConfigRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.GetWorkflowConfigRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.GetWorkflowConfigResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    stagesList: jspb.Message.toObjectList(msg.getStagesList(),
    proto.automatedcodingworkflow.Stage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigResponse}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.GetWorkflowConfigResponse;
  return proto.automatedcodingworkflow.GetWorkflowConfigResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigResponse}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.automatedcodingworkflow.Stage;
      reader.readMessage(value,proto.automatedcodingworkflow.Stage.deserializeBinaryFromReader);
      msg.addStages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.GetWorkflowConfigResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.GetWorkflowConfigResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.automatedcodingworkflow.Stage.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Stage stages = 1;
 * @return {!Array<!proto.automatedcodingworkflow.Stage>}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.getStagesList = function() {
  return /** @type{!Array<!proto.automatedcodingworkflow.Stage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.automatedcodingworkflow.Stage, 1));
};


/**
 * @param {!Array<!proto.automatedcodingworkflow.Stage>} value
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigResponse} returns this
*/
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.setStagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.automatedcodingworkflow.Stage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.automatedcodingworkflow.Stage}
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.addStages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.automatedcodingworkflow.Stage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.automatedcodingworkflow.GetWorkflowConfigResponse} returns this
 */
proto.automatedcodingworkflow.GetWorkflowConfigResponse.prototype.clearStagesList = function() {
  return this.setStagesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.automatedcodingworkflow.Stage.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.Stage.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.Stage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.Stage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.Stage.toObject = function(includeInstance, msg) {
  var f, obj = {
    stageName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    stageClass: jspb.Message.getFieldWithDefault(msg, 2, ""),
    stagesList: jspb.Message.toObjectList(msg.getStagesList(),
    proto.automatedcodingworkflow.Stage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.Stage}
 */
proto.automatedcodingworkflow.Stage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.Stage;
  return proto.automatedcodingworkflow.Stage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.Stage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.Stage}
 */
proto.automatedcodingworkflow.Stage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStageName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStageClass(value);
      break;
    case 3:
      var value = new proto.automatedcodingworkflow.Stage;
      reader.readMessage(value,proto.automatedcodingworkflow.Stage.deserializeBinaryFromReader);
      msg.addStages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.Stage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.Stage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.Stage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.Stage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStageName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStageClass();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getStagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.automatedcodingworkflow.Stage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string stage_name = 1;
 * @return {string}
 */
proto.automatedcodingworkflow.Stage.prototype.getStageName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.automatedcodingworkflow.Stage} returns this
 */
proto.automatedcodingworkflow.Stage.prototype.setStageName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string stage_class = 2;
 * @return {string}
 */
proto.automatedcodingworkflow.Stage.prototype.getStageClass = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.automatedcodingworkflow.Stage} returns this
 */
proto.automatedcodingworkflow.Stage.prototype.setStageClass = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated Stage stages = 3;
 * @return {!Array<!proto.automatedcodingworkflow.Stage>}
 */
proto.automatedcodingworkflow.Stage.prototype.getStagesList = function() {
  return /** @type{!Array<!proto.automatedcodingworkflow.Stage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.automatedcodingworkflow.Stage, 3));
};


/**
 * @param {!Array<!proto.automatedcodingworkflow.Stage>} value
 * @return {!proto.automatedcodingworkflow.Stage} returns this
*/
proto.automatedcodingworkflow.Stage.prototype.setStagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.automatedcodingworkflow.Stage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.automatedcodingworkflow.Stage}
 */
proto.automatedcodingworkflow.Stage.prototype.addStages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.automatedcodingworkflow.Stage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.automatedcodingworkflow.Stage} returns this
 */
proto.automatedcodingworkflow.Stage.prototype.clearStagesList = function() {
  return this.setStagesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.SetWorkspacePathRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    workspacePath: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathRequest}
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.SetWorkspacePathRequest;
  return proto.automatedcodingworkflow.SetWorkspacePathRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathRequest}
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorkspacePath(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.SetWorkspacePathRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorkspacePath();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string workspace_path = 1;
 * @return {string}
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.prototype.getWorkspacePath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathRequest} returns this
 */
proto.automatedcodingworkflow.SetWorkspacePathRequest.prototype.setWorkspacePath = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.automatedcodingworkflow.SetWorkspacePathResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    success: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    errorMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathResponse}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.automatedcodingworkflow.SetWorkspacePathResponse;
  return proto.automatedcodingworkflow.SetWorkspacePathResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathResponse}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setSuccess(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setErrorMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.automatedcodingworkflow.SetWorkspacePathResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.automatedcodingworkflow.SetWorkspacePathResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSuccess();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getErrorMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional bool success = 1;
 * @return {boolean}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.getSuccess = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/**
 * @param {boolean} value
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathResponse} returns this
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.setSuccess = function(value) {
  return jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string error_message = 2;
 * @return {string}
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.getErrorMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.automatedcodingworkflow.SetWorkspacePathResponse} returns this
 */
proto.automatedcodingworkflow.SetWorkspacePathResponse.prototype.setErrorMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


goog.object.extend(exports, proto.automatedcodingworkflow);
